# Generated by Django 2.0.2 on 2018-02-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=50)),
                ('confpassword', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=200, null=True)),
            ],
        ),
    ]
