# Generated by Django 2.0.2 on 2018-03-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_auto_20180316_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('session_id', models.CharField(db_index=True, max_length=200)),
                ('session_data', models.TextField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
