# Generated by Django 2.0.2 on 2018-03-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0004_auto_20180325_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='user_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
