# Generated by Django 2.0.2 on 2018-03-26 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0005_auto_20180325_1419'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersession',
            unique_together={('id', 'user_id')},
        ),
    ]
