# Generated by Django 2.0.2 on 2018-03-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstore', '0005_auto_20180307_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
