# Generated by Django 2.0.2 on 2018-03-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstore', '0009_auto_20180314_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
